version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      PORT: 8000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      URLS: "[{ url: 'http://localhost:8000/swagger.json' }]"
